#
# Defines environment variables.
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='vimpager'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

# A better LC_CTYPE
export LC_CTYPE="en_US.UTF-8"

# Set the list of directories that Zsh searches for programs.
path=(
  $HOME/bin
  /usr/local/{bin,sbin}
  /usr/local/opt/go/libexec/bin
  $path
)

# export SSL_CERT_FILE=/usr/local/opt/curl-ca-bundle/share/ca-bundle.crt

export NVM_DIR="/Users/xav/.nvm"

# Useful for Karma, as Chrome is installed via Cask
export CHROME_BIN=CHROME_BIN=~/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome

#erlang
MANPATH=/usr/local/opt/erlang/lib/erlang/man:$MANPATH

# unset because homebrew fails to download because of certificates
# (remove and brew install anything --force to test)
unset CURL_CA_BUNDLE
unset SSL_CERT_FILE

# Vagrant configuration to save some space on the hard drive
export VAGRANT_HOME=/Volumes/External/Work/vagrant/
export MACHINE_STORAGE_PATH=/Volumes/External/Work/docker-machine/

source $HOME/.cargo/env
if [ -x /usr/libexec/java_home ]; then
  export JAVA_HOME="`/usr/libexec/java_home -v '1.8*'`"
fi
